### ISSUE TITLE
DBsplit needed before HPC.daligner draft ?

### ISSUE THREAD

**Issue by agroppi** [HingeAssembler/HINGE#61]
Hi,

Step by step I'm running HINGE
Thank to @govinda-kamath and @ilanshom (https://github.com/fxia22/HINGE/issues/60) I was able to reach the "get consensus assembly" step.
But I'm facing this error : 

 # Daligner jobs (3)
daligner -A -k20 -h50 -e0.85 vriparia_test.1 draft
daligner: Block draft contains reads < 20bp long !  Run DBsplit.
daligner -A -k20 -h50 -e0.85 vriparia_test.2 draft
daligner: Block draft contains reads < 20bp long !  Run DBsplit.
daligner -A -k20 -h50 -e0.85 vriparia_test.3 draft
daligner: Block draft contains reads < 20bp long !  Run DBsplit.
daligner -A -k20 -h50 -e0.85 vriparia_test.4 draft
daligner: Block draft contains reads < 20bp long !  Run DBsplit.
daligner -A -k20 -h50 -e0.85 vriparia_test.5 draft
daligner: Block draft contains reads < 20bp long !  Run DBsplit.
daligner -A -k20 -h50 -e0.85 vriparia_test.6 draft
daligner: Block draft contains reads < 20bp long !  Run DBsplit.
daligner -A -k20 -h50 -e0.85 vriparia_test.7 draft
daligner: Block draft contains reads < 20bp long !  Run DBsplit.
daligner -A -k20 -h50 -e0.85 vriparia_test.8 draft
daligner: Block draft contains reads < 20bp long !  Run DBsplit.
daligner -A -k20 -h50 -e0.85 vriparia_test.9 draft
daligner: Block draft contains reads < 20bp long !  Run DBsplit.

Do I have to run DBsplit like in the initial step ? : 

`DBsplit draft -x500 -s200`

Thanks

**Comment by agroppi** [comment]
I try to add 
`DBsplit draft -x500 -s200`
It works.
But after that I had a problem
the flas files were note named as described in your demo run

I had to put : `LAmerge vriparia_test.draft.las vriparia_test.*.draft.las` instead of `LAmerge draft.vriparia_test.las draft.vriparia_test.*.las`

But now another seg fault error :( : 

get consensus assembly: Thu Sep 1 14:57:10 CEST 2016
#############################
Merge the .las files <parts> into a singled sorted file: Thu Sep 1 14:57:10 CEST 2016
length threshold:4000
1 files
1 files
# Contigs:219
# Reads:250846
# Alignments:434105
/var/lib/torque/mom_priv/jobs/32990.jarvis.SC: line 102: 59593 Segmentation fault      (core dumped) /home/ag/rainman_home/HINGE/build/bin/consensus/consensus draft vriparia_test vriparia_test.draft.las vriparia_test.consensus.fasta /home/ag/rainman_home/HINGE/utils/nominal.ini

For info; here are the files I have : 

-rw-r--r-- 1 ag users   11  1 sept. 14:57 vriparia_test_consensus.gfa
-rw-r--r-- 1 ag users    0  1 sept. 14:57 vriparia_test.consensus.fasta
-rw-r--r-- 1 ag users  38M  1 sept. 14:57 vriparia_test.draft.las
-rw-r--r-- 1 ag users 2,7M  1 sept. 14:34 vriparia_test.9.draft.las
-rw-r--r-- 1 ag users 4,7M  1 sept. 14:34 vriparia_test.8.draft.las
-rw-r--r-- 1 ag users 4,7M  1 sept. 14:34 vriparia_test.7.draft.las
-rw-r--r-- 1 ag users 4,5M  1 sept. 14:34 vriparia_test.6.draft.las
-rw-r--r-- 1 ag users 4,0M  1 sept. 14:34 vriparia_test.5.draft.las
-rw-r--r-- 1 ag users 4,3M  1 sept. 14:34 vriparia_test.4.draft.las
-rw-r--r-- 1 ag users 4,2M  1 sept. 14:34 vriparia_test.3.draft.las
-rw-r--r-- 1 ag users 4,5M  1 sept. 14:34 vriparia_test.2.draft.las
-rw-r--r-- 1 ag users 4,4M  1 sept. 14:34 vriparia_test.1.draft.las
-rw-r--r-- 1 ag users  167  1 sept. 14:28 draft.db
-rw-r--r-- 1 ag users 6,2M  1 sept. 10:23 vriparia_test.draft.pb.fasta
-rw-r--r-- 1 ag users 9,3K  1 sept. 10:23 draft_map.txt
-rw-r--r-- 1 ag users 6,1M 31 août  23:41 vriparia_test.draft.fasta

**Comment by ilanshom** [comment]
Hi Alexis,

Sorry about that, and thanks for all the details. We have another dataset here where we are getting the same error. We will fix that as soon as possible and get back to you.

ilan

**Comment by MichaelsGITIGIT** [comment]
Also getting segfault at consensus step...

**Comment by govinda-kamath** [comment]
We've pushed a fix to this. It should work now. Please let us know if there are issues.

**Comment by MichaelsGITIGIT** [comment]
Thx. Will test as soon as I have access to my machine.

**Comment by MichaelsGITIGIT** [comment]
Are you sure that this line in `get_consensus_gfa.py` has to be a static path:
`cols = np.loadtxt('/data/pacbio_assembly/pb_data/yeast/draft_map.txt', dtype=str,usecols=(1,))`

Anyway, the "new" get_consensus_gfa.py throws me an error because of this...

**Comment by govinda-kamath** [comment]
You're right. That was a big bug. I've fixed it now.

**Comment by agroppi** [comment]
Hi,

Still having a seg fault after your update ...

get consensus assembly: Mon Sep 5 09:20:43 CEST 2016
#############################
Merge the .las files <parts> into a singled sorted file: Mon Sep 5 09:20:43 CEST 2016
length threshold:4000
1 files
1 files
# Contigs:219
# Reads:250846
# Alignments:434105
/var/lib/torque/mom_priv/jobs/32998.jarvis.SC: line 102: 74327 Segmentation fault      (core dumped) /home/ag/rainman_home/HINGE/build/bin/consensus/consensus draft vriparia_test vriparia_test.draft.las vriparia_test.consensus.fasta /home/ag/rainman_home/HINGE/utils/nominal.ini

**Comment by MichaelsGITIGIT** [comment]
Works now. Is it normal that the consensus fasta has double the assembly size than the actual genome?
Or does the algorithm have a problem fusing pos/neg strand? Or "too much" data?

**Comment by ilanshom** [comment]
@MichaelsGITIGIT the size is doubled because we keep the two orientations as separate nodes on the graph. The algorithm doesn't have a problem fusing the strands, we just find that the graph representation where the two strands are separated has some advantages. In particular, it allows one to represent the assembly as a directed graph, which allows one to visually follow the sequence direction (as a directed path on the graph) and makes the loop resolution steps that our assembler uses (explained in the [paper](http://biorxiv.org/content/early/2016/08/01/062117)) easier to implement.

@agroppi, we are looking into that and will get back to you asap

**Comment by MichaelsGITIGIT** [comment]
OK, strange... Now that I do the whole process with the newest check-out from git I get segmentation fault again :-( But not sure why...

**Comment by ilanshom** [comment]
@agroppi, sorry for the delay in responding. We think the error has to do with the way we are handling very short contigs in the consensus. We should be able to fix it soon. Could you please send us the files `draft_map.txt` and `*.edges.list` for us to test? Thanks.

**Comment by agroppi** [comment]
@ilanshom Here are the files
Thanks for your help
[files.zip](https://github.com/fxia22/HINGE/files/471482/files.zip)

**Comment by fxia22** [comment]
Hi @agroppi , we have updated the draft assembly module, can you take a look at if that still produces seg fault? Thanks!

**Comment by agroppi** [comment]
@fxia22 
OK, Many thanks.
I'll try and I will keep you informed

Alexis

**Comment by agroppi** [comment]
@fxia22 

Unfortunatly same problem with get_consensus_gfa.py

#############################
get consensus gfa: Fri Sep 23 13:34:57 CEST 2016
Traceback (most recent call last):
  File "/home/ag/rainman_home/HINGE/scripts/get_consensus_gfa.py", line 62, in <module>
    nodes_to_keep = [x for x in g.nodes() if consensus_contigs[g.node[x]['contig_id']] != '' ]
IndexError: list index out of range
Exit Code: 1

I attach also the full log

Regards

Alexis
[Log.zip](https://github.com/fxia22/HINGE/files/491005/Log.zip)

**Comment by agroppi** [comment]
I have also this error with get_draft_path.py

get draft assembly : Fri Sep 23 11:01:04 CEST 2016
Traceback (most recent call last):
  File "/home/ag/rainman_home/HINGE/scripts/get_draft_path.py", line 126, in <module>
    out_graph.node[vert]['cut_end'] = min([out_graph.edge[vert][x]['read_a_match_start'] for x in out_graph.successors(vert)])
KeyError: 'read_a_match_start'

**Comment by fxia22** [comment]
You may need to generate the graph again because we also updated hinging and pruning_and_clipping. 

Regards,
Fei

**Comment by agroppi** [comment]
Sadly ... discouraging ...
Please find here my script.sh and the error log
Thanks again for watching this
Regards
Alexis
PS : The first steps (correct_head.py ; fasta2DB ; DBsplit and HPC.daligner have been already run before)

[log.zip](https://github.com/fxia22/HINGE/files/498234/log.zip)
[script.zip](https://github.com/fxia22/HINGE/files/498233/script.zip)

**Comment by fxia22** [comment]
@agroppi are you sure you are using the latest commit? Because this bug should have been resolved in our previous commit:
`terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi`

can you show us the `.edges.list ` file? Thanks!

**Comment by agroppi** [comment]
@fxia22 
OK I will try a fresh new install.

**Comment by fxia22** [comment]
@agroppi we handled this problem. Can you try again to see if this issue remains? Thanks!

**Comment by agroppi** [comment]
@fxia22 
downloaded and installed a fresh new version.
I will give it a try
In the step "get consensus assembly"
Is the command : 
`HPC.daligner <db_name> draft | zsh -v` 
correct ? I was questionning me about the "draft" option. I can't find it in the github of HPC.daligner ...  ?
Thanks

**Comment by govinda-kamath** [comment]
> Is the command :
HPC.daligner <db_name> draft | zsh -v
correct ? I was questionning me about the "draft" option. I can't find it in the github of HPC.daligner ... ?
Shouldn't it be "<db_name>.draft" ?

It should be 
```
HPC.daligner <db_name> draft | zsh -v
```
<db_name> refers to the name of the `db` of reads. Draft is the `db` of the draft assembly. This step is mapping the reads back onto the draft assembly for improving the consensus.

> At the "get draft assembly"
Instead of "ecoli<identifier-of-run>.G2.graphml"
Shouldn't it be "<ecoli_<identifier-of-run>.G2.graphml" ?

It should be `ecoli<identifier-of-run>.G2.graphml`. You can give `_` in your identifier though if you like.

**Comment by agroppi** [comment]
OK thanks.
The example lacks a preliminary steps I had to perform : 
correct head of the pacbio reads
But the command : `hinge correct-head` doesn't work 
I had to perform this step with `HINGE/scripts/correct_head.py`

**Comment by agroppi** [comment]
OK thanks.
The pipeline is running.
I had to perform correct read as a preliminary step.
I hope it will go till the end.
